import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*  /!*<link rel="stylesheet" href="/css/global.css" />*!/*/}
      {/*</Head>*/}


        <Layout>

            <h1>
                Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

        </Layout>



    </div>
  )
}
